import random
funny_quotes = [
    "When life gives you lemons, squeeze them into your enemy's eye.",
    "Always remember you're unique... just like everyone else.",
    "If at first you don't succeed, then skydiving definitely isn't for you.",
    "Don't take life too seriously. No one gets out alive anyway.",
    "Follow your dreams! Except that one where you're naked at work.",
    "The road to success is always under construction.",
    "If you think nobody cares if you're alive, try missing a couple of car payments.",
    "I used to think I was indecisive, but now I'm not so sure.",
    "Procrastinate now, don't put it off.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I don't need a hair stylist, my pillow gives me a new hairstyle every morning.",
    "Why do they call it beauty sleep when you wake up looking like a troll?",
    "My bed is a magical place where I suddenly remember everything I forgot to do.",
    "Common sense is like deodorant. The people who need it most never use it.",
    "Life is short. Smile while you still have teeth.",
    "I’m on a 30-day diet. So far, I’ve lost 15 days.",
    "I could be a morning person if morning happened around noon.",
    "A balanced diet means a cupcake in each hand.",
    "I put my phone in airplane mode, but it’s not flying!",
    "I'm not lazy, I'm on energy-saving mode.",
    "The older I get, the earlier it gets late.",
    "I'm on a whiskey diet. I've lost three days already.",
    "They say ‘don’t try this at home’… so I’m coming over to your house to try it.",
    "My favorite exercise is a cross between a lunge and a crunch. I call it lunch.",
    "Dear Math, I’m not a therapist. Solve your own problems.",
    "I’m not a complete idiot; some parts are missing.",
    "I don’t have an attitude problem. You have a perception problem.",
    "If I was funny, I would have a good quote for this space.",
    "The first five days after the weekend are always the hardest.",
    "I didn’t fall. I’m just spending some quality time with the floor.",
    "I'm on a seafood diet. I see food and eat it.",
    "We never really grow up, we only learn how to act in public.",
    "I would agree with you, but then we’d both be wrong.",
    "Of course I talk to myself. Sometimes I need expert advice.",
    "I told my computer I needed a break, and now it won’t stop sending me Kit Kats.",
    "I wonder how many miles I’ve scrolled with my thumb.",
    "I'm not clumsy, the floor just hates me, the table and chairs are bullies, and the walls get in my way.",
    "Maybe you should eat some makeup so you can be pretty on the inside, too.",
    "I used to be indecisive. Now I’m not sure.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "Life is too short to be serious all the time. So, if you can’t laugh at yourself, call me—I’ll laugh at you.",
    "If you think nothing is impossible, try slamming a revolving door.",
    "Artificial intelligence is no match for natural stupidity.",
    "I don’t suffer from insanity; I enjoy every minute of it.",
    "Money can’t buy happiness, but it can buy a lot of chocolate, which is kind of the same thing.",
    "I love deadlines. I love the whooshing noise they make as they go by.",
    "I'm not shy, I'm holding back my awesomeness so I don't intimidate you.",
    "I'd agree with you, but then we'd both be wrong."
]

def lambda_handler (event, context):
    random_num = random.randint(0, len(funny_quotes))
    return {
        "status" : 200,
        "message" : funny_quotes[random_num]
        }